<?php
$cfg['secfile']['java_pubder']=$_SERVER['DOCUMENT_ROOT'].__CFG_document_place__.'/settings/key/ibistu_publicKey.der';
$cfg['secfile']['java_pubpem']=$_SERVER['DOCUMENT_ROOT'].__CFG_document_place__.'/settings/key/ibistu_publicKey.pem';
$cfg['secfile']['java_prider']=$_SERVER['DOCUMENT_ROOT'].__CFG_document_place__.'/settings/key/ibistu_privateKey.der';
$cfg['secfile']['java_pripem']=$_SERVER['DOCUMENT_ROOT'].__CFG_document_place__.'/settings/key/ibistu_privateKey.pem';
$cfg['secfile']['js_key']=$_SERVER['DOCUMENT_ROOT'].__CFG_document_place__.'/settings/key/RSA.json';
$cfg['secfile']['ios_pubder']=$_SERVER['DOCUMENT_ROOT'].__CFG_document_place__.'/settings/key/ibistu_publicKey_ios.der';
$cfg['secfile']['ios_pubderbase64']=$_SERVER['DOCUMENT_ROOT'].__CFG_document_place__.'/settings/key/ibistu_publicKey_ios.derb64';
$cfg['secfile']['ios_pubpem']=$_SERVER['DOCUMENT_ROOT'].__CFG_document_place__.'/settings/key/ibistu_publicKey_ios.pem';
$cfg['secfile']['ios_pripem']=$_SERVER['DOCUMENT_ROOT'].__CFG_document_place__.'/settings/key/ibistu_privateKey_ios.pem';
?>